--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Books" (
    "Id" integer NOT NULL,
    "Author" text,
    "Title" text,
    "PublishedYear" integer NOT NULL
);


ALTER TABLE public."Books" OWNER TO postgres;

--
-- Name: Books_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Books" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Books_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Books; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Books" ("Id", "Author", "Title", "PublishedYear") FROM stdin;
1	Stephen King	Golden Years	1991
2	Avi Silberschatz	Database System Concepts	2019
3	Bill Karwin	SQL Antipatterns, Avoiding the Pitfalls of Database Programming	2023
4	J.K. Rowling	Harry Potter and the Sorcerer's Stone	1997
5	J.R.R. Tolkien	The Hobbit	1937
6	George Orwell	1984	1949
7	F. Scott Fitzgerald	The Great Gatsby	1925
8	Harper Lee	To Kill a Mockingbird	1960
9	Jane Austen	Pride and Prejudice	1813
10	Mark Twain	The Adventures of Tom Sawyer	1876
11	Herman Melville	Moby Dick	1851
12	Isaac Asimov	Foundation	1951
13	Ray Bradbury	Fahrenheit 451	1953
14	Gabriel Garcia Marquez	One Hundred Years of Solitude	1967
15	Leo Tolstoy	War and Peace	1869
16	Charles Dickens	A Tale of Two Cities	1859
17	Virginia Woolf	Mrs. Dalloway	1925
18	J.D. Salinger	The Catcher in the Rye	1951
19	Stephen King	The Shining	1977
20	Agatha Christie	Murder on the Orient Express	1934
21	Franz Kafka	The Metamorphosis	1915
22	H.G. Wells	The Time Machine	1895
23	Dante Alighieri	The Divine Comedy	1320
24	Herman Hesse	Steppenwolf	1927
25	Gabriel Garcia Marquez	Love in the Time of Cholera	1985
26	C.S. Lewis	The Lion, the Witch and the Wardrobe	1950
27	Kurt Vonnegut	Slaughterhouse-Five	1969
28	Margaret Atwood	The Handmaid's Tale	1985
29	John Steinbeck	Of Mice and Men	1937
30	F. Scott Fitzgerald	Tender is the Night	1934
31	Cormac McCarthy	The Road	2006
32	Haruki Murakami	Norwegian Wood	1987
33	Chuck Palahniuk	Fight Club	1996
34	Dan Brown	The Da Vinci Code	2003
35	Suzanne Collins	The Hunger Games	2008
36	Rick Riordan	The Lightning Thief	2005
37	John Green	The Fault in Our Stars	2012
38	Danielle Steel	The Ghost	2007
39	Colleen Hoover	It Ends with Us	2016
40	Toni Morrison	Beloved	1987
41	Maya Angelou	I Know Why the Caged Bird Sings	1969
42	Margaret Atwood	Oryx and Crake	2003
43	David Mitchell	Cloud Atlas	2004
44	Neil Gaiman	American Gods	2001
45	Philip K. Dick	Do Androids Dream of Electric Sheep?	1968
46	Louisa May Alcott	Little Women	1868
47	Emily Bronte	Wuthering Heights	1847
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20241012212433_LibraryDB	8.0.10
\.


--
-- Name: Books_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Books_Id_seq"', 47, true);


--
-- Name: Books PK_Books; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Books"
    ADD CONSTRAINT "PK_Books" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

